@startuml
'https://plantuml.com/sequence-diagram

actor user
activate main
activate screen_manager
entity player_manager
entity enemy_manager

user -> main: start

main -> screen_manager: create
loop run
    alt game_page
        user -> screen_manager: game_page
        loop not(live = 0 or clear)
            alt len(enemy_manager) = 0
                alt level % 5 = 0
                    screen_manager -> explain_page: summary()
                    explain_page -> screen_manager: back()
                    screen_manager -> player_manager: upgrade()
                end
                screen_manager -> enemy_manager: upgrade()
                screen_manager -> screen_manager: play()
            end
            screen_manager -> screen_manager: draw()
            user -> player_manager: move()
        else
            screen_manager -> screen_manager: game_over
        end
    else select other_page
        user -> screen_manager: other_page
        screen_manager -> main: loading_page
    end
    main -> user: exit
end


@enduml